In [1]:
# This mounts your Google Drive to the Colab VM.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
FOLDERNAME ='hw1/'
assert FOLDERNAME is not None, "[!] Enter the foldername."

# Now that we've mounted your Drive, this ensures that
# the Python interpreter of the Colab VM can load
# python files from within it.
import sys
sys.path.append('/content/drive/My Drive/{}'.format(FOLDERNAME))

In [3]:
# Importing necessary libraries
import cv2
import glob
from matplotlib import pyplot as plt
from PIL import Image
import PIL
from numpy import asarray
import numpy as np

In [4]:
from google.colab.patches import cv2_imshow

In [5]:
#############################CAT PART##################################################    
data=[]
for name in glob.glob('drive/MyDrive/hw1/cat/*jpg'):
    
    img_cat = Image.open(name)
    data_cat = np.array(img_cat)
    image = cv2.imread(name)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #cv2_imshow(image)
    #cv2_imshow(gray)
    data_cat1d=data_cat.flatten()
    #artik label atamasi yapiyorum
    data_label_cat=np.append(data_cat1d,0)
    print(data_label_cat)
    data.append(data_label_cat)

 

[89 93 79 ... 48 43  0]
[ 50  80  56 ... 113 130   0]
[176 131 102 ... 247 250   0]
[168 170 157 ... 178 159   0]
[125 139 140 ...   9   4   0]
[172 168 159 ... 131 134   0]
[253 253 253 ... 253 253   0]
[79 74 71 ... 82 63  0]
[  7   9   8 ... 169 161   0]
[  0   0   9 ... 107  82   0]
[153 161 182 ... 227 196   0]
[107 118 122 ...  73  62   0]
[67 82 23 ... 61 51  0]
[197 151  76 ... 228 201   0]
[193 178 173 ... 179 174   0]
[233 255 191 ...  85  81   0]
[180 168 152 ... 129 120   0]
[218 224 250 ...  15  15   0]
[156 151 147 ...  63  39   0]
[  5  16  12 ... 123 131   0]
[208 194 145 ...  37  22   0]
[ 47  40  48 ... 173 184   0]
[122 124 119 ... 239 240   0]
[68 49 16 ...  8 25  0]
[ 16  18  17 ... 102  91   0]
[78 88 98 ... 24 17  0]
[204 204 204 ...  70  78   0]
[141 149 112 ... 167 143   0]
[56 70 97 ... 50 77  0]
[38 40 37 ...  4  0  0]
[86 79 63 ...  1  4  0]
[167 155 133 ...  83  47   0]
[ 1  2 82 ...  1 39  0]
[92 61 40 ... 83 84  0]
[178 209 211 ... 213 198   0]
[197 198 1

In [6]:
print(data_cat1d.size) #sukurler olsun dustu tek boyuta

270000


In [7]:
#############################RABBIT PART##################################################    
for name in glob.glob('drive/MyDrive/hw1/rabbit/*jpg'):
    img_rab = Image.open(name)
    data_rab = np.array(img_rab)
    image = cv2.imread(name)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #cv2_imshow(image)
    #cv2_imshow(gray)
    data_rab1d=data_rab.flatten()
    #artik label atamasi yapiyorum
    data_label_rab=np.append(data_rab1d,1)
    #print(data_label_rab)
    data.append(data_label_rab)

    
  

In [27]:
#data=np.vstack((data_label_cat,data_label_rab))
data=np.array(data)
np.random.shuffle(data)

cut_val=int(data.shape[0]*0.9)
#print(cut_val)
train_set=data[0:cut_val,:]
test_set=data[0:-int(len(data)*0.1),:]
print(test_set.shape)


(1440, 270001)


In [ ]:
testdata=100
rows = test_set[:testdata, :] 
acc=np.zeros(10)
i=-1
for k in range(1,20,2):
 i=i+1
 c=0
 for n in range(len(rows)):

   pt=test_set[n-1,:300*300] 
 #Euclidean distance
   d=np.sqrt(np.sum(np.square(train_set[:,:300*300]-pt),axis=1)) 
   z=train_set[:,-1]
   dlabel=np.transpose(np.vstack((d,z)))
 #label  
   sortedarr = dlabel[dlabel[:,0].argsort()]
   vote=sum(sortedarr[:k,1])/k
   if vote < 0.5 :
     pt1=np.zeros(1) 
     pt1=np.ones(1)
   corr=rows[n-1,np.size(rows,1)-1]-pt1

   if corr==0:
     c=c+1
 acc[i]=(c/testdata)*100